<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lukas Arnold">
<meta name="author" content="Simone Arnold">
<meta name="author" content="Florian Bagemihl">
<meta name="author" content="Matthias Baitsch">
<meta name="author" content="Marc Fehr">
<meta name="author" content="Maik Poetzsch">
<meta name="author" content="Sebastian Seipel">

<title>Werkzeugbaustein Pseudocode</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Pseudocode_files/libs/clipboard/clipboard.min.js"></script>
<script src="Pseudocode_files/libs/quarto-html/quarto.js"></script>
<script src="Pseudocode_files/libs/quarto-html/popper.min.js"></script>
<script src="Pseudocode_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Pseudocode_files/libs/quarto-html/anchor.min.js"></script>
<link href="Pseudocode_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Pseudocode_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Pseudocode_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Pseudocode_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Pseudocode_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<meta name="mermaid-theme" content="neutral">
<script src="Pseudocode_files/libs/quarto-diagram/mermaid.min.js"></script>
<script src="Pseudocode_files/libs/quarto-diagram/mermaid-init.js"></script>
<link href="Pseudocode_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#voraussetzungen" id="toc-voraussetzungen" class="nav-link active" data-scroll-target="#voraussetzungen"><span class="header-section-number">1</span> Voraussetzungen</a></li>
  <li><a href="#lernziele" id="toc-lernziele" class="nav-link" data-scroll-target="#lernziele"><span class="header-section-number">2</span> Lernziele</a></li>
  <li><a href="#was-ist-pseudocode" id="toc-was-ist-pseudocode" class="nav-link" data-scroll-target="#was-ist-pseudocode"><span class="header-section-number">3</span> Was ist Pseudocode?</a>
  <ul class="collapse">
  <li><a href="#pseudocode-von-einfach-bis-ausführlich" id="toc-pseudocode-von-einfach-bis-ausführlich" class="nav-link" data-scroll-target="#pseudocode-von-einfach-bis-ausführlich">Pseudocode von einfach bis ausführlich</a></li>
  </ul></li>
  <li><a href="#pseudocode-erstellen" id="toc-pseudocode-erstellen" class="nav-link" data-scroll-target="#pseudocode-erstellen"><span class="header-section-number">4</span> Pseudocode erstellen</a>
  <ul class="collapse">
  <li><a href="#übungsaufgaben" id="toc-übungsaufgaben" class="nav-link" data-scroll-target="#übungsaufgaben"><span class="header-section-number">4.1</span> Übungsaufgaben</a></li>
  <li><a href="#mit-eva-zum-fokussprint" id="toc-mit-eva-zum-fokussprint" class="nav-link" data-scroll-target="#mit-eva-zum-fokussprint"><span class="header-section-number">4.2</span> Mit EVA zum Fokussprint</a>
  <ul class="collapse">
  <li><a href="#fokussprint" id="toc-fokussprint" class="nav-link" data-scroll-target="#fokussprint">Fokussprint</a></li>
  </ul></li>
  <li><a href="#programmbeschreibung-in-pseudocode" id="toc-programmbeschreibung-in-pseudocode" class="nav-link" data-scroll-target="#programmbeschreibung-in-pseudocode"><span class="header-section-number">4.3</span> Programmbeschreibung in Pseudocode</a>
  <ul class="collapse">
  <li><a href="#karel-the-robot" id="toc-karel-the-robot" class="nav-link" data-scroll-target="#karel-the-robot">Karel The Robot</a></li>
  </ul></li>
  <li><a href="#programmablauf-visualisieren" id="toc-programmablauf-visualisieren" class="nav-link" data-scroll-target="#programmablauf-visualisieren"><span class="header-section-number">4.4</span> Programmablauf visualisieren</a>
  <ul class="collapse">
  <li><a href="#werkzeuge-zur-erstellung-von-flussdiagrammen" id="toc-werkzeuge-zur-erstellung-von-flussdiagrammen" class="nav-link" data-scroll-target="#werkzeuge-zur-erstellung-von-flussdiagrammen">Werkzeuge zur Erstellung von Flussdiagrammen</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#musterlösungen" id="toc-musterlösungen" class="nav-link" data-scroll-target="#musterlösungen"><span class="header-section-number">5</span> Musterlösungen</a></li>
  <li><a href="#das-wichtigste" id="toc-das-wichtigste" class="nav-link" data-scroll-target="#das-wichtigste"><span class="header-section-number">6</span> Das Wichtigste</a></li>
  <li><a href="#lernzielkontrolle" id="toc-lernzielkontrolle" class="nav-link" data-scroll-target="#lernzielkontrolle"><span class="header-section-number">7</span> Lernzielkontrolle</a>
  <ul class="collapse">
  <li><a href="#kompetenzquiz" id="toc-kompetenzquiz" class="nav-link" data-scroll-target="#kompetenzquiz"><span class="header-section-number">7.1</span> Kompetenzquiz</a></li>
  <li><a href="#übungen" id="toc-übungen" class="nav-link" data-scroll-target="#übungen"><span class="header-section-number">7.2</span> Übungen</a>
  <ul class="collapse">
  <li><a href="#börsenstrategie-entwickeln" id="toc-börsenstrategie-entwickeln" class="nav-link" data-scroll-target="#börsenstrategie-entwickeln">Börsenstrategie entwickeln</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Andere Formate</h2><ul><li><a href="Pseudocode.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Werkzeugbaustein Pseudocode</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor:innen</div>
    <div class="quarto-title-meta-contents">
             <p>Lukas Arnold </p>
             <p>Simone Arnold </p>
             <p>Florian Bagemihl </p>
             <p>Matthias Baitsch </p>
             <p>Marc Fehr </p>
             <p>Maik Poetzsch </p>
             <p>Sebastian Seipel </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Veröffentlichungsdatum</div>
    <div class="quarto-title-meta-contents">
      <p class="date">8. Oktober 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<!-- Blocksatz / justify text -->
<div class="cell">
<style type="text/css">
p {
  text-align: justify /* alternativ: start, end, center */
  
}
</style>
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
<div id="Lizenz" class="border">
<!-- Die Lizenz wird manuell in einer Div erstellt, um Vorgaben für OER hinsichtlich Position und Format zu entsprechen. (licence key im YAML-Header funktioniert in PDF nicht.) -->
<div>

</div>
<div class="quarto-layout-panel" data-layout="[20, 80]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 20.0%;justify-content: flex-start;">
<p><img src="skript/00-bilder/CC-BY.svg" class="img-fluid" alt="Symbol des Lizenzhinweises Creative Commons BY"> <!-- Grafik ohne Titel und Dateiendung einbinden --></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 80.0%;justify-content: flex-start;">
<p>Bausteine Computergestützter Datenanalyse von Lukas Arnold, Simone Arnold, Florian Bagemihl, Matthias Baitsch, Marc Fehr, Maik Poetzsch und Sebastian Seipel. Werkzeugbaustein Pseudocode von Maik Poetzsch ist lizensiert unter <a href="https://creativecommons.org/licenses/by/4.0/deed.de">CC BY 4.0</a>. Das Werk ist abrufbar auf <a href="https://github.com/bausteine-der-datenanalyse">GitHub</a>. Ausgenommen von der Lizenz sind alle Logos und anders gekennzeichneten Inhalte. 2024</p>
</div>
</div>
</div>
<p>Zitiervorschlag</p>
<p>Arnold, Lukas, Simone Arnold, Matthias Baitsch, Marc Fehr, Maik Poetzsch, und Sebastian Seipel. 2024. „Bausteine Computergestützter Datenanalyse. Werkzeugbaustein Pseudocode“. <a href="https://github.com/bausteine-der-datenanalyse/w-pseudocode" class="uri">https://github.com/bausteine-der-datenanalyse/w-pseudocode</a>.</p>
</div>
<div style="page-break-after: always;"></div>
<section id="voraussetzungen" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Voraussetzungen</h1>
<p>Für die Bearbeitung dieses Bausteins bestehen keine Voraussetzungen. Die Bearbeitungszeit beträgt je nach Umfang der bearbeiteten Übungsaufgaben circa 120 bis 300 Minuten.</p>
<p>Während der Bearbeitung des Bausteins <em>können</em> Flussdiagramme unter anderem mit Python oder R erstellt werden. Dazu werden folgende Bibliotheken benötigt:</p>
<ul>
<li><p>Python: <a href="https://pypi.org/project/schemdraw/">Schemdraw</a> und/oder <a href="https://pypi.org/project/graphviz/">graphviz</a>. Zur Ausführung von Graphviz wird außerdem eine lokale Installation des Programms <a href="https://www.graphviz.org/">Graphviz</a> benötigt.</p></li>
<li><p>R: <a href="https://cran.r-project.org/web/packages/DiagrammeR/index.html">DiagrammeR</a></p></li>
</ul>
<p>Am Ende des Bausteins besteht die Möglichkeit, ein Programm zur Überprüfung einer Börsenstrategie zu entwickeln. Zur Veranschaulichung wird ein Auszug aus der von Robert Shiller erstellten Datei <code>ie_data.xls</code> mit historischen Börsenkursen des S&amp;P 500 verwendet. Die Datei kann unter <a href="https://shillerdata.com/" class="uri">https://shillerdata.com/</a> bezogen werden.</p>
</section>
<section id="lernziele" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Lernziele</h1>
<p>In diesem Baustein lernen Sie, mit Hilfe von Pseudocode (komplexe) Aufgabenstellungen zu strukturieren und Schritt für Schritt ein Programm für die computergestützte Datenanalyse zu entwickeln. Außerdem lernen Sie, den Programmablauf für das eigene Verständnis und den Austausch mit Dritten in Form eines Flussdiagramms zu visualisieren.</p>
<p>Wenn Sie dieses Modul durchgearbeitet haben, können Sie …</p>
<ul>
<li><p>die Entwicklung von Pseudocode als Kreativitätstechnik einsetzen,</p></li>
<li><p>ein Programm in Pseudocode beschreiben,</p></li>
<li><p>ein Programm in abgegrenzte Zwischenschritte aufteilen und diese in eine zweckmäßige Reihenfolge bringen,</p></li>
<li><p>die Abhängigkeiten zwischen den Zwischenschritten beschreiben,</p></li>
<li><p>die Voraussetzungen für die Ausführung jedes Zwischenschritts und des gesamten Programms benennen sowie</p></li>
<li><p>den Programmablauf als Flussdiagramm visualisieren.</p></li>
</ul>
<p>Schlagworte: Ideen entwickeln, Programmbeschreibung, Pseudocode, Programmablaufplan, DIN 66001</p>
</section>
<section id="was-ist-pseudocode" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Was ist Pseudocode?</h1>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="/skript/00-bilder/festmahl-PCL.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>&nbsp;</figcaption>
</figure>
</div>
<div class="border">
<p>Toast Dining Eating von OpenClipart-Vectors ist lizensiert unter <a href="https://pixabay.com/service/license-summary/">Pixabay Content License</a>. Das Werk ist abrufbar auf <a href="https://pixabay.com/vectors/toast-dining-eating-event-festive-153723/">Pixabay</a>.</p>
</div>
<p>&nbsp;</p>
<p>Denken Sie an die Zubereitung eines Festtagsmahls. Sie haben im Internet ein Rezept gefunden, alle Zutaten von der Zutatenliste eingekauft und beginnen entsprechend der angegebenen Zubereitungszeit vor der Ankunft Ihrer Gäste zu kochen. Klingt gut, oder? Nun, dieses Vorgehen verspricht hungrig wartende Gäste, denn Rezepte sind häufig keine fertige Schritt-für-Schritt-Anleitung, sondern erfordern einige Vorarbeit:</p>
<ul>
<li><p>Mal fehlen Zutaten auf der Zutatenliste, mal bleibt eine zu besorgende Zutat im Rezept unerwähnt und am Ende übrig. Im vierten Schritt ruht der Teig bereits seit zwei Stunden im Kühlschrank und der Ofen ist schon auf 250 Grad vorgeheizt. Eine vollständige Aufgabenbeschreibung erfordert Vorbereitung: Nur wer alle Abhängigkeiten kennt, wird pünktlich fertig.</p></li>
<li><p>In der Küche gilt eine eigene Fachsprache: Wissen Sie, was blanchieren bedeutet, wieso selbst sauberes Gemüse geputzt werden soll, wann Nudeln al dente sind oder ob die Soße erst lichterloh brennen sollte, damit man sie ablöschen kann? Falls nicht, ist zunächst etwas Übersetzungsarbeit in eine für Sie verständliche Sprache gefragt.</p></li>
<li><p>Wer kein Messer hat, kann kein Brot schneiden: Die Zutaten sind nicht alles, zu einem gelungenen Gericht gehört auch das richtige Werkzeug. Haben Sie alles in der Küche, was Sie zur Zubereitung brauchen?</p></li>
</ul>
<p>Kurz: Sie brauchen einen eigenen Plan – nicht nur beim Kochen, sondern auch bei der computergestützten Datenanalyse. Denn auch die Datenanalyse erfolgt selten linear. Stattdessen wechseln sich Schritte zur Organisation, Visualisierung, Auswertung und Weiterverarbeitung von Daten ab. Dazu steht eine Vielzahl unterschiedlicher Programme mit eigener Syntax zur Auswahl. Oder ist eine selbst geschriebene Funktion besser geeignet? Häufig liegen Daten in unterschiedlichen Formaten vor und müssen für die Verwendung spezialisierter Programme transformiert werden. Dies sind typische Herausforderungen der Datenanalyse, die durch eine gute Planung aufgefangen werden können. Bei der Planung hilft Ihnen Pseudocode.</p>
<p>Pseudocode beschreibt ein Programm und informatische Konzepte in einer leicht verständlichen, alltäglichen Sprache. Die Entwicklung von Pseudocode kann sowohl als Kreativitätstechnik als auch als Schablone zur strukturierten Lösung von Aufgabenstellungen genutzt werden. Pseudocode erlaubt es, sich zunächst auf die konzeptionelle Lösung einer Aufgabenstellung und die Planung des Programmaufbaus zu fokussieren. Dies kann sinnvoll sein, um durch die Unterteilung des Programms in Zwischenschritte die Entwicklung zu vereinfachen, benötigte Programme, Pakete und Methoden zu identifizieren oder den Arbeitsaufwand abzuschätzen.</p>
<p>Pseudocode ist auch ein Instrument, um sich mit Dritten über ein Programm auszutauschen, zum Beispiel um ein Problem im Code zu erörtern. Denn Pseudocode setzt keine Kenntnis einer bestimmten Programmiersprache voraus und ist intuitiv verständlich. Zur Unterstützung der Kommunikationsfunktion von Pseudocode kann dieser zum Beispiel als Flussdiagramm visualisiert werden.</p>
<div id="imp-Pseudocode" class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition&nbsp;1: Pseudocode
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pseudocode beschreibt einen Lösungsweg für informatische Aufgabenstellungen in formalisierter Alltagssprache statt mit den Ausdrücken und der Syntax einer Programmiersprache. Das Präfix pseudo stammt aus dem Griechischen und bedeutet falsch oder nur so aussehen als ob. Pseudocode ist ‚falscher‘ Programmcode, der mit natürlicher Sprache gebildet wird. <span class="citation" data-cites="Pseudocode-was-ist">(<a href="#ref-Pseudocode-was-ist" role="doc-biblioref">AAU 2019</a>)</span> Pseudocode ist darüber hinaus auch ein Kommunikationsmittel, um sich mit anderen über informatische Probleme und deren Lösung auszutauschen (z. B. Kommiliton:innen, Betreuer:innen).</p>
</div>
</div>
<section id="pseudocode-von-einfach-bis-ausführlich" class="level3">
<h3 class="anchored" data-anchor-id="pseudocode-von-einfach-bis-ausführlich">Pseudocode von einfach bis ausführlich</h3>
<p>In welcher Form und wie detailliert Sie Pseudocode formulieren, ist abhängig von Ihrem Kenntnisstand und Ihrem Ziel: Für die Strukturierung Ihres Programms in aufeinanderfolgende Zwischenschritte und die Identifizierung von Abhängigkeiten ist eine einfache Auflistung von Arbeitsschritten ausreichend. Für die Entwicklung eines Algorithmus sowie die Identifizierung von benötigten Methoden (z. B. Schleifen) und Werkzeugen (z. B. spezialisierte Pakete) wird es erforderlich sein, Programmanweisungen detaillierter zu beschreiben. Eine ausführliche Darstellung hilft Ihnen zum Beispiel, wiederkehrende Arbeitsschritte zu identifizieren, die in eine Funktion ausgelagert werden können. Für die Präsentation Ihres Programms auf einer Fachtagung oder die Dokumentation in einem Benutzer:innenhandbuch kann ein Flussdiagramm zweckmäßig sein.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">einfach</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">mittel</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">ausführlich</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false" href="">Flussdiagramm</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>Programmanweisung mit sprechendem Namen</p>
<p><code>SortiereAufsteigend</code></p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>Anweisungsblock in Alltagssprache</p>
<pre><code>  SortiereAufsteigend
    DurchlaufeDatensatz (LängeDatensatz - 1) mal # Anzahl Wiederholungen
      Von Anfang bis (LängeDatensatz - 1) # Paarweise Vergleiche
        Vergleiche Wert und Nachfolger
        WENN Wert größer als Nachfolger DANN
          Vertausche Wert und Nachfolger
    AusgabeDatensatz </code></pre>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<p>Anweisungsblock im Stil und mit Begriffen der Programmierung</p>
<pre><code>
  SortiereAufsteigend  
    WENN LängeDatensatz &gt; 1 DANN
      VON Datensatz[IndexA = 1] BIS Datensatz [IndexA = LängeDatensatz - 1] TUE # Anzahl Schleifendurchläufe
        VON Datensatz[IndexB = 1] BIS Datensatz [IndexB = LängeDatensatz - 1] TUE # Paarweise Vergleiche
          WENN Datensatz[IndexB] &gt; Datensatz[IndexB + 1] DANN
            Vertausche(Datensatz[IndexB], Datensatz[IndexB + 1])
              Schreibe(Datensatz[IndexB], nach = Zwischenlager)
              Schreibe(Datensatz[IndexB + 1], nach = Datensatz[IndexB])
              Schreibe(Zwischenlager, nach = Datensatz[IndexB + 1])
          WENN IndexB &lt; LängeDatensatz - 1 DANN
            Erhöhe IndexB
      WENN IndexA &lt; LängeDatensatz - 1 DANN
        Erhöhe IndexA
    AusgabeDatensatz</code></pre>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skript/00-bilder/flussdiagramm-bubblesort-ms-mp.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Flussdiagramm Sortiere Aufsteigend</figcaption>
</figure>
</div>
<div class="border">
<p>Flussdiagramm von Marc Sönnecken und Maik Poetzsch</p>
</div>
</div>
</div>
</div>
<p>&nbsp;</p>
</section>
</section>
<section id="pseudocode-erstellen" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Pseudocode erstellen</h1>
<p>Das im Folgenden vorgestellte Schema unterstützt Sie dabei, Ideen zu entwickeln, ein Programm zu beschreiben und den Programmablauf zu visualisieren. Pseudocode hilft Ihnen, Ihr Programm sowie die benötigten Werkzeuge und Methoden in einer für Sie und Dritte verständlichen Weise zu beschreiben. Wie Sie Pseudocode verfassen, ist eine individuelle Angelegenheit, denn für die Erstellung von Pseudocode gibt es nur wenige Regeln. Pseudocode soll vor allem Ihnen helfen, einen Lösungsweg für eine Aufgabenstellung zu entwickeln. Pseudocode ist dann ‚richtig‘ geschrieben, wenn er Ihnen hilft:</p>
<ul>
<li><p>Ihre Gedanken zu fokussieren,</p></li>
<li><p>eine Aufgabenstellung für Sie nachvollziehbar zu beschreiben,</p></li>
<li><p>die Aufgabenstellung in abgegrenzte Teilaufgaben zu untergliedern,</p></li>
<li><p>für die Teilaufgaben eine Lösungsvorschrift (Algorithmus) zu entwickeln,</p></li>
<li><p>benötigte Methoden und Werkzeuge zu identifizieren,</p></li>
<li><p>Ihre Lösungsvorschriften als ein Programm aufeinanderfolgender Arbeitsschritte zu beschreiben,</p></li>
<li><p>den Zeitaufwand für die Umsetzung abzuschätzen sowie</p></li>
<li><p>sich mit Dritten über Ihr Programm auszutauschen.</p></li>
</ul>
<section id="übungsaufgaben" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="übungsaufgaben"><span class="header-section-number">4.1</span> Übungsaufgaben</h2>
<p>Für die Bearbeitung dieses Bausteins stehen zwei Übungsaufgaben zur Auswahl. Die Übungsaufgaben sprechen auch Studierende ohne Vorkenntnisse in der Datenanalyse an und verdeutlichen Teilaspekte der Programmentwicklung. Am besten eignet sich jedoch ein eigenes Projekt, das Sie bearbeiten möchten. Dazu haben Sie im Reiter “Eigenes Projekt” die Möglichkeit, eine eigene Aufgabenstellung zu formulieren.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Übersicht</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Eigenes Projekt</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false" href="">Hefezopf backen</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-4" role="tab" aria-controls="tabset-2-4" aria-selected="false" href="">Vitamin C bei Meerschweinchen</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<ul>
<li><p>ohne Vorkenntnisse Datenanalyse: Hefezopf backen<br>
Lernziele: Aufgabenstellung in aufeinanderfolgende Arbeitsschritte untergliedern, Arbeitsschritte vollständig beschreiben, Abhängigkeiten und Voraussetzungen identifizieren (benötigte Werkzeuge identifizieren, Zeitaufwand schätzen)</p></li>
<li><p>mit Vorkenntnissen Datenanalyse: Vitamin C bei Meerschweinchen<br>
Lernziele: Datenanalyse in Pseudocode beschreiben.</p></li>
</ul>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<p>Hier können Sie die Aufgabenstellung bzw. das Ziel Ihres Projekts festhalten. Bitte beachten Sie, dass Ihr Text nicht gespeichert wird.</p>
<textarea id="“own-project”" name="“own-project”" rows="4" cols="50"></textarea>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<p>Ihre Freundin Lisa schickt Ihnen ein Rezept, dass Sie im Internet gefunden hat. Sie schreibt, dass Sie morgen schon eine Stunde früher zum geplanten Treffen kommen kann, um vorher gemeinsam mit Ihnen zu backen – zu zweit würde man schon schneller fertig werden als in den im Rezept angegebenen 65 Minuten. Lisa fragt auch, ob Sie noch Zutaten mitbringen soll.</p>
<p><strong>Wie antworten Sie Lisa? Modellieren Sie den Backprozess.</strong></p>
<div class="border">
<p>Das folgende Rezept wurde von Anna-Lena erstellt und ist abrufbar unter <a href="https://www.einfachbacken.de/rezepte/hefezopf" class="uri">https://www.einfachbacken.de/rezepte/hefezopf</a>.</p>
<p><strong><em>Zarter Hefezopf</em></strong><br>
Arbeitszeit 40 Min.<br>
Backen 25 Min.</p>
<table class="table">
<thead>
<tr class="header">
<th>Zutaten</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>250 ml</td>
<td>Milch</td>
</tr>
<tr class="even">
<td>475 g</td>
<td>Weizenmehl (Type 405)</td>
</tr>
<tr class="odd">
<td>60 g</td>
<td>Zucker</td>
</tr>
<tr class="even">
<td>½ Würfel</td>
<td>frische Hefe (ca. 21 g)</td>
</tr>
<tr class="odd">
<td>50 g</td>
<td>weiche Butter (Zimmertemperatur)</td>
</tr>
<tr class="even">
<td>1 Prise</td>
<td>Salz</td>
</tr>
<tr class="odd">
<td>1</td>
<td>Ei (Gr. M)</td>
</tr>
<tr class="even">
<td></td>
<td>etwas Milch zum Bestreichen</td>
</tr>
<tr class="odd">
<td></td>
<td>etwas Hagelzucker zum Bestreuen</td>
</tr>
<tr class="even">
<td></td>
<td>etwas Mehl zur Teigverarbeitung</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<p><strong>1. Schritt</strong></p>
<p><strong>250 ml</strong> Milch, <strong>475 g</strong> Weizenmehl (Type 405), <strong>1 Prise</strong> Zucker, <strong>½ Würfel</strong> frische Hefe (ca. 21 g)</p>
<p>Milch erwärmen bis sie lauwarm ist. Mehl in eine Schüssel sieben. Eine Mulde darin bilden und die Hefe in die Mulde bröseln. 3 EL von der lauwarmen Milch mit 1 Prise Zucker vermischen und über die Hefe in der Mulde gießen. Mit einem Löffel die Hefe-Milchmischung etwas vermischen (noch nicht das Mehl einkneten). Die Schüssel mit einem Geschirrhandtuch abdecken und an einem warmen Ort ca. 15 Min. gehen lassen.</p>
<p><strong>2. Schritt</strong></p>
<p><strong>1</strong> Ei (Gr. M), <strong>60 g</strong> Zucker, <strong>1 Prise</strong> Salz, <strong>50 g</strong> weiche Butter (Zimmertemperatur)</p>
<p>Ei, restliche Milch, restlichen Zucker und Salz in die Schüssel geben und zusammen mit der Hefemischung und dem Mehl 3 Min. auf niedriger Stufe, dann ca. 5 Min. auf hoher Stufe mit den Knethaken des Rührgeräts verkneten. Butter in Stücken nach und nach unterkneten. Damit der Teig später gut aufgeht, sollte der Teig mindestens 5 Min. kräftig geknetet werden. Sonst kann der Teig später zusammenfallen oder klebrig sein!</p>
<p><strong>3. Schritt</strong></p>
<p>etwas Mehl zur Teigverarbeitung</p>
<p>Schüssel mit dem Teig nochmals mit einem Geschirrhandtuch abdecken und weitere 60 Min. an einem warmen Ort gehen lassen. Dann den[ ]Teig auf eine bemehlte Arbeitsfläche geben und in drei Teile teilen. Die Teigstücke jeweils zu einer langen Wurst mit 40 cm Länge rollen. Teigsträhnen zu einem Zopf flechten. Die Enden miteinander verdrehen und unter den Zopf legen, damit sie einen schönen Abschluss bilden. Zopf auf ein mit Backpapier belegtes Blech legen und mit einem Geschirrhandtuch abdecken. Nochmals 45 Min. gehen lassen.</p>
<p><strong>4. Schritt</strong></p>
<p>etwas Milch zum Bestreichen, etwas Hagelzucker zum Bestreuen</p>
<p>Währenddessen den Backofen auf <strong>200 Grad Ober-/ Unterhitze (Umluft: 180 Grad)</strong> vorheizen. Zopf mit etwas Milch bestreichen und mit Hagelzucker bestreuen. Zopf schließlich im vorgeheizten Ofen <strong>ca. 15-20 Minuten</strong> leicht bräunlich backen. Vollständig auskühlen lassen. Der Zopf kann auch wunderbar eingefroren werden.</p>
</div>
</div>
<div id="tabset-2-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-4-tab">
<p>In einer Gruppe von 60 Meerschweinchen wurde die Länge der zahnbildenden Zellen (Odontoblasten) in Micron gemessen (<strong>len</strong>). Den Tieren wurde zuvor Vitamin C in Form von Ascorbinsäure (VC) oder Orangensaft (VC) verabreicht (<strong>supp</strong>). Die Meerschweinchen erhielten Dosen von 0.5, 1 oder 2 Milligramm Vitamin C pro Tag (<strong>dose</strong>). <span class="citation" data-cites="Crampton.1947">(<a href="#ref-Crampton.1947" role="doc-biblioref">Crampton 1947</a>)</span></p>
<p><strong>Welche Wirkung hat Vitamin C auf das Zahnwachstum von Meerschweinchen? Erläutern Sie Ihr Vorgehen mit Hilfe von Pseudocode oder mit Hilfe eines Flussdiagramms, um den Effekt der Verabreichungsart und der Dosis zu bestimmen.</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>#</th>
<th>len</th>
<th>supp</th>
<th>dose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>4.2</td>
<td>VC</td>
<td>0.5</td>
</tr>
<tr class="even">
<td>11</td>
<td>16.5</td>
<td>VC</td>
<td>1</td>
</tr>
<tr class="odd">
<td>21</td>
<td>23.6</td>
<td>VC</td>
<td>2</td>
</tr>
<tr class="even">
<td>31</td>
<td>15.2</td>
<td>OJ</td>
<td>0.5</td>
</tr>
<tr class="odd">
<td>41</td>
<td>19.7</td>
<td>OJ</td>
<td>1</td>
</tr>
<tr class="even">
<td>51</td>
<td>25.5</td>
<td>OJ</td>
<td>2</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<p>Wenn Sie sich den vollständigen Datensatz ansehen möchten, können Sie diesen in R mit <code>ToothGrowth</code> aufrufen oder den Datensatz hier herunterladen: <a href="https://vincentarelbundock.github.io/Rdatasets/csv/datasets/ToothGrowth.csv">ToothGrowth.csv</a></p>
</div>
</div>
</div>
</section>
<section id="mit-eva-zum-fokussprint" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="mit-eva-zum-fokussprint"><span class="header-section-number">4.2</span> Mit EVA zum Fokussprint</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skript/00-bilder/adam-eve-PCL-de.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>&nbsp;</figcaption>
</figure>
</div>
<div class="border">
<p>Adam Bible Nature von CCXpistiavos ist lizensiert unter <a href="https://pixabay.com/service/license-summary/">Pixabay Content License</a>. Das Werk ist abrufbar auf <a href="https://pixabay.com/vectors/adam-bible-bible-pics-2061819/">Pixabay</a>. Die Sprechblase wurde ergänzt.</p>
</div>
<p>&nbsp;</p>
<p>Manchmal ist aller Anfang schwer. Der erste Schritt zur Programmentwicklung besteht in der Ideensammlung: Was soll genau getan werden, welche Schritte sind dafür erforderlich, was kann bereits erledigt werden, was muss noch vorbereitet oder recherchiert werden? <strong>Wenn Sie bereits eine gute Vorstellung von der Aufgabenlösung haben, können Sie diesen Schritt überspringen.</strong></p>
<p>Der <strong>Fokussprint</strong> (Scheuermann 2016) ist eine schnelle Schreibdenkübung, um einen Einstieg ins Schreiben zu einem bestimmten Thema zu finden. Die Übung kann als Kreativitätstechnik für den Einstieg in ein Thema, aber auch zwischendurch als Denkhilfe eingesetzt werden. Es geht dabei darum, mit einem hohen Schreibtempo drauflos zu schreiben. Dadurch schreiben Sie nahe an Ihrer inneren Sprache und Ihre Kreativität kann freien Lauf nehmen. <span class="citation" data-cites="Scheuermann2016">(<a href="#ref-Scheuermann2016" role="doc-biblioref">Scheuermann 2016, 74, 78</a>)</span></p>
<p>Der Fokussprint wird in zwei Schritten durchgeführt: Der erste Schritt besteht in einer fünfminütigen Schreibphase. Formulieren Sie auf einem Blatt Papier oder am Computer die Aufgabenstellung oder das Problem, zu dem Sie Ihre Gedanken sammeln möchten. Hier können Sie sich mit einem Stichwort kurzfassen oder eine konkrete Frage formulieren. Stellen Sie sich einen Wecker auf 5 Minuten und beginnen mit dem Schnellschreiben auf dem vorbereiteten Blatt. Es gibt nur eine Regel: Wenn Sie bemerken, dass Ihre Gedanken vom Thema der Überschrift abschweifen, besinnen Sie sich auf das Thema, zum Beispiel, indem Sie die Aufgabenstellung erneut aufschreiben (einfach dort, wo Sie gerade schreiben). <span class="citation" data-cites="Scheuermann2016">(<a href="#ref-Scheuermann2016" role="doc-biblioref">Scheuermann 2016, 78</a>)</span></p>
<section id="fokussprint" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="fokussprint">Fokussprint</h3>
<p><strong>In diesem Textfeld können Sie Ihren Fokussprint durchführen. Bitte beachten Sie, dass Ihr Text nicht gespeichert wird.&nbsp;Also dann: 3, 2, 1 – schreiben Sie in eigenen Worten los!</strong></p>
<textarea id="focussprint-textarea" name="“focussprint-textarea”" rows="4" cols="50"></textarea>
<p>&nbsp;</p>
<p>Im zweiten Schritt erfolgt die Auswertung. Lesen Sie Ihren Fokussprint durch und markieren Sie, was Ihnen wichtig erscheint. Können Sie Zwischenschritte identifizieren? Wenn ja, markieren Sie diese und fügen Ergänzungen, Kommentare oder Fragen hinzu. <span class="citation" data-cites="Scheuermann2016">(vgl. <a href="#ref-Scheuermann2016" role="doc-biblioref">Scheuermann 2016, 78</a>)</span></p>
<div id="tip-Zwischenschritte" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;2: Zwischenschritte identifizieren
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Zwischenschritte teilen eine komplexe Aufgabenstellung in überschaubare Arbeitspakete auf, die jeweils eine bestimmte Funktion im Programmablauf erfüllen (z. B. das Sortieren von Daten) oder ein bestimmtes Arbeitsergebnis erzeugen (z. B. eine Grafik). Ein Zwischenschritt ist also ein Unterprogramm und bei der Bildung von Zwischenschritten geht es somit darum, eine Aufgabenstellung in Teilaufgaben aufzuteilen und eine Vorstellung davon zu gewinnen, welche Arbeitsschritte in einem Unterprogramm ausgeführt werden müssen, um die Teilaufgabe zu lösen.</p>
<p>Die Bildung von Zwischenschritten dient vor allem der Komplexitätsreduktion. Ein zur Lösung einer abgegrenzten Teilaufgabe entwickeltes Unterprogramm hat zum einen den Vorteil, dass es leicht getestet werden kann, um Fehler zu finden und zu beheben. Zum anderen kann ein Unterprogramm wiederholt im Programmablauf aufgerufen werden, z. B. um die Lösung einer anderen, komplexeren Teilaufgabe zu vereinfachen.</p>
<p>Bei der Abgrenzung von Zwischenschritten können auch andere Kriterien als die erbrachte Funktion oder das produzierte Arbeitsergebnis sinnvoll sein, etwa nach dem Ort der Datenverarbeitung (z. B. an der Messstelle, am Arbeitsrechner, im Rechenzentrum) oder nach den verwendeten Werkzeugen (z. B. Mikrocontroller, Python, C++, manuelle Datenverarbeitung).</p>
<div id="tip-Übungsaufgaben" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;1: Mögliche Zwischenschritte für die Übungsaufgaben
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Hefezopf backen</p>
<ul>
<li><p>Unterteilung nach Funktion: Vorbereiten der Zutaten, Verarbeiten der Zutaten, Backen</p></li>
<li><p>Unterteilung nach Arbeitsergebnissen: Milchmischung zubereiten, Hefemischung zubereiten, Rohteig zubereiten, Teigzopf formen, Zopf backen</p></li>
</ul>
<p>Vitamin C bei Meerschweinchen</p>
<ul>
<li><p>Unterteilung nach Funktion: Teildatensätze bilden, Datensatz auswerten, Datensatz darstellen, Flussdiagramm erstellen</p></li>
<li><p>Unterteilung nach Arbeitsergebnis: tabellierter Mittelwertvergleich, Boxplot für alle Teilgruppen, Mermaid Flussdiagramm</p></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
<p>Das <strong>EVA-Prinzip</strong> hilft Ihnen, Zwischenschritte vollständig zu beschreiben. Das EVA-Prinzip ist ein Grundmuster der computergestützten Datenverarbeitung und steht für <strong>E</strong>ingabe, <strong>V</strong>erarbeitung und <strong>A</strong>usgabe. Diese Schritte folgen aufeinander: Zuerst werden die Daten erfasst, dann erfolgt die Datenverarbeitung, zuletzt werden die Ergebnisse ausgegeben.</p>
<ul>
<li><p>Eingabe: Welche Daten liegen als Eingabe vor? Welches Format haben die Daten?</p></li>
<li><p>Verarbeitung: Welche Arbeitsschritte müssen durchgeführt werden, um die beschriebene Ausgabe zu erreichen?</p></li>
<li><p>Ausgabe: Welches Ergebnis soll durch die Datenverarbeitung erzeugt werden? Welches Format hat die Ausgabe?</p></li>
</ul>
<p>Fassen Sie zum Abschluss Ihren Fokussprint in einem Kernsatz zusammen, der das für Sie Wichtigste hervorhebt. Dies kann eine Feststellung, aber auch eine offene Frage, die Sie weiter verfolgen möchten, sein. Markieren Sie diesen Kernsatz zusätzlich. <span class="citation" data-cites="Scheuermann2016">(<a href="#ref-Scheuermann2016" role="doc-biblioref">Scheuermann 2016, 79</a>)</span></p>
<p>Damit haben Sie den ersten Schritt zur Formulierung einer vollständigen Programmbeschreibung geschafft! Wenn Sie möchten, können Sie Ihre Gedanken zu einer noch offenen Frage oder zu einem Zwischenschritt mit einem erneuten Fokussprint vertiefen. Andernfalls folgt nun der nächste Schritt.</p>
</section>
</section>
<section id="programmbeschreibung-in-pseudocode" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="programmbeschreibung-in-pseudocode"><span class="header-section-number">4.3</span> Programmbeschreibung in Pseudocode</h2>
<p>Sie haben nun eine Vorstellung von Ihrem Lösungsweg, den Zwischenschritten, aus denen dieser besteht, und von ihrer Abfolge. Im zweiten Schritt wird Ihr Programm durch die Beschreibung mit Pseudocode formalisiert. Dazu werden Programmanweisungen zwar alltagssprachlich, aber im Stil und mit Begriffen der Programmierung formuliert. Dies bedeutet,</p>
<ol type="1">
<li><p>für Programmanweisungen sprechende Namen zu vergeben. In der Datenanalyse benutzte Anweisungen sind:</p>
<ul>
<li><p>Daten importieren (import), z. B. HoleDatenVonOrt</p></li>
<li><p>Daten organisieren (tidy), z. B. SortiereAufsteigend</p></li>
<li><p>Daten transformieren (transform), z. B. BildeDurchschnitt</p></li>
<li><p>Daten visualisieren (visualise), z. B. ErzeugeHistogramm</p></li>
<li><p>Daten modellieren (model), z. B. ErzeugeLinearesModell</p></li>
<li><p>Daten exportieren (export), z. B. SpeicherePlot</p></li>
</ul>
<p><span class="citation" data-cites="R-for-Data-Science">(vgl. <a href="#ref-R-for-Data-Science" role="doc-biblioref">Wickham, Çetinkaya-Rundel, und Grolemund 2023</a>, Kapitel Whole game)</span></p></li>
<li><p>den Programmablauf zu dokumentieren, indem</p>
<ul>
<li><p>aufeinanderfolgende Programmanweisungen untereinandergeschrieben,</p></li>
<li><p>Blöcke von Programmanweisungen durch Einrückung und/oder Einklammerung kenntlich gemacht und</p></li>
<li><p>zusammenhängende Programmanweisungen in abgegrenzten Zwischenschritten gruppiert werden.</p></li>
</ul></li>
<li><p>Programmanweisungen von erläuternden Teilen durch Kommentare zu trennen, indem</p>
<ul>
<li><p>Kommentare durch Sonderzeichen gekennzeichnet, beispielsweise <code>// Kommentar</code>, <code># Kommentar</code>, <code>%% Kommentar</code> oder <code>/* Kommentar */</code>, und</p></li>
<li><p>einzelnen Arbeitsschritten vorangestellt (z. B. Kurzbeschreibung von Zwischenschritten nach EVA) und/oder innerhalb einer Zeile benutzt werden.</p></li>
</ul></li>
<li><p>Komplexe Programmanweisungen mit informatischen Begriffen auszudrücken, ggf. in Anlehnung an die Begriffe und Syntax der von Ihnen gewählten Programmiersprache. Dies umfasst:</p>
<p><strong>Fallunterscheidungen:</strong> Fallunterscheidungen machen die Ausführung von Programmanweisungen abhängig von einer oder von mehreren Bedingungen.</p>
<ul>
<li><p>WENN A (kleiner, kleiner gleich, genau gleich, größer als, größer gleich, ungleich) B, DANN C, SONST D</p></li>
<li><p>WENN A B1 UND B2, DANN C</p></li>
<li><p>WENN A B1 ODER B2, DANN C</p></li>
</ul>
<p><strong>Schleifen:</strong> Schleifen wiederholen Programmanweisungen solange die Eintrittsbedingung gilt bzw. die Abbruchbedingung eintritt.</p>
<ul>
<li><p>SOLANGE A, TUE C</p></li>
<li><p>VON A BIS B, TUE C</p></li>
</ul>
<p><strong>Funktionen:</strong> Funktionen bündeln Programmanweisungen, damit Programmteile mehrfach verwendet werden können. Funktionen sind eine Form von Unterprogrammen.</p>
<ul>
<li>FunktionTueXY(Argument 1, Argument 2, …)<br>
Anweisung1<br>
Anweisung2<br>
…</li>
</ul></li>
</ol>
<div id="nte-beispiel-pseudocode" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Beispiel&nbsp;1: Programmbeschreibung in Pseudocode
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code># Eingabe: eindimensionaler, ordinaler Datensatz
# Verarbeitung: Prüfung ob Datensatz mindestens zwei Werte enthält
## falls nein: Fehlermeldung
## falls ja: aufsteigende Sortierung mit Bubblesort mit Kontrollstruktur für den äußeren Schleifendurchlauf
# Ausgabe: aufsteigend sortierter Datensatz

  SortiereAufsteigend(Datensatz)
    WENN LängeDatensatz &gt; 1 DANN

      # äußere Schleife
      do_work = WAHR # Kontrollstruktur für die äußere Schleife
      WENN do_work == WAHR DANN

        VON Datensatz[IndexA = 1] BIS Datensatz [IndexA = LängeDatensatz - 1] TUE
          do_work = FALSCH

          # innere Schleife für paarweise Vergleiche
          VON Datensatz[IndexB = 1] BIS Datensatz [IndexB = LängeDatensatz - 1] TUE
            WENN Datensatz[IndexB] &gt; Datensatz[IndexB + 1] DANN
              Vertausche(Datensatz[IndexB], Datensatz[IndexB + 1])
                Schreibe(Datensatz[IndexB], nach = Zwischenlager)
                Schreibe(Datensatz[IndexB + 1], nach = Datensatz[IndexB])
                Schreibe(Zwischenlager, nach = Datensatz[IndexB + 1])
              do_work = WAHR # merke, wenn etwas vertauscht wurde
            WENN IndexB &lt; LängeDatensatz - 1 DANN
              Erhöhe IndexB
          
          WENN IndexA &lt; LängeDatensatz - 1 DANN
            Erhöhe IndexA

      AusgabeDatensatz
    SONST
      Melde("Der Datensatz muss mindenstens zwei Elemente enthalten!")
</code></pre>
<p><em>Hinweis: Die manuelle Erhöhung der Zählindizes ist bei Programmiersprachen in der Regel nicht erforderlich und dient nur der besseren Verständlichkeit</em>.</p>
</div>
</div>
</div>
<p>Mit der Formalisierung Ihres Programms in Pseudocode haben Sie eine intuitiv verständliche, vollständige Programmbeschreibung entwickelt. Im nächsten Schritt können Sie Ihr Programm grafisch darstellen.</p>
<p>&nbsp;</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">Übungsaufgabe zählen</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">Musterlösung Pseudocode</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<p><strong>Beschreiben Sie ein Programm, das von 1-10 und von 15 bis 20 zählt, in Pseudocode.</strong></p>
<p>In diesem Textfeld können Sie Ihren Pseudocode schreiben. Bitte beachten Sie, dass Ihr Text nicht gespeichert wird.</p>
<textarea id="exercise-area2" name="“exercise-area2”" rows="4" cols="50"></textarea>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<pre><code>i = 0
SOLANGE i kleiner als 10 TUE
  erhöhe i um 1
  Ausgabe i
i = 14
SOLANGE i kleiner als 20 TUE
  erhöhe i um 1
  Ausgabe i</code></pre>
</div>
</div>
</div>
<section id="karel-the-robot" class="level3">
<h3 class="anchored" data-anchor-id="karel-the-robot">Karel The Robot</h3>
<p>Wenn Sie die Anwendung informatischer Konzepte wie Fallunterscheidung oder Schleifen üben möchten, ist <a href="https://github.com/fredoverflow/karel">Karel The Robot</a> einen Blick wert. Das Programm führt mit einer eigenen Pseudocode-Sprache in die Anwendung informatischer Kontrollstrukturen ein.</p>
<p>Eine Vorstellung des Programms, Hinweise zur Installation und Bedienung finden Sie auf der im vorherigen Absatz verlinkten GitHub-Seite oder auf dem YouTube-Kanal der Medienberatung Niedersachsen:</p>
<div class="border">
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/vD8RN_WbvLo" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>Programmieren lernen mit Karel von Medienberatung Niedersachsen ist lizensiert unter <a href="https://creativecommons.org/licenses/by/4.0/">CC-BY</a>. Das Werk ist abrufbar auf <a href="https://www.youtube.com/watch?v=vD8RN_WbvLo">YouTube</a>. 2022</p>
</div>
</section>
</section>
<section id="programmablauf-visualisieren" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="programmablauf-visualisieren"><span class="header-section-number">4.4</span> Programmablauf visualisieren</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skript/00-bilder/woman-speaker.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>&nbsp;</figcaption>
</figure>
</div>
<div class="border">
<p>Lead 1 von CocoMaterial ist lizensiert unter <a href="https://creativecommons.org/publicdomain/zero/1.0/">CC0 1.0</a>. Das Werk ist abrufbar auf <a href="https://cocomaterial.com/results?q=megaphone&amp;vectorId=65">CocoMaterial</a>.</p>
</div>
<p>&nbsp;</p>
<p>Eine anschauliche grafische Darstellung verhilft Pseudocode zu noch mehr Klarheit und unterstützt dadurch insbesondere den Austausch mit Dritten. Die grafische Darstellung eines Programms wird Programmablaufplan oder Flussdiagramm genannt. Die für einen Programmablaufplan verwendeten Symbole sind in der <span class="citation" data-cites="DIN-66001-1983">(<a href="#ref-DIN-66001-1983" role="doc-biblioref">DIN 1983</a>)</span> genormt. Die Formen werden auch als Knoten (nodes) bezeichnet, die Verbindungen als Kanten (edges).</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[30, 70]">
<div class="quarto-layout-row">
<div class="cell quarto-layout-cell" style="flex-basis: 30.0%;justify-content: flex-start;">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
  A([Start / Stopp])
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 70.0%;justify-content: flex-start;">
<dl>
<dt>Rechteck mit gerundeten Seiten (Nummer 6.4.1)</dt>
<dd>
Grenzstelle zur Umwelt, die Beginn und Ende einer Folge anzeigt und beispielsweise Herkunft oder Verbleib von Daten signalisiert.
</dd>
</dl>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell quarto-layout-cell" style="flex-basis: 30.0%;justify-content: flex-start;">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
  A[Verarbeitung]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 70.0%;justify-content: flex-start;">
<dl>
<dt>Rechteck (Nummer 6.1.1)</dt>
<dd>
Verarbeitung einschließlich Ein-/Ausgabe
</dd>
</dl>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell quarto-layout-cell" style="flex-basis: 30.0%;justify-content: flex-start;">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
  A{Entscheidung}
  B[Anweisung 1]
  C[Anweisung 2]

  A --&gt;|wahr| B
  A --&gt;|falsch| C
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 70.0%;justify-content: flex-start;">
<dl>
<dt>Raute (Nummer 6.1.2)</dt>
<dd>
Verzweigung/Entscheidung
</dd>
</dl>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell quarto-layout-cell" style="flex-basis: 30.0%;justify-content: flex-start;">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
  subgraph Unterprogramm [Kaffee kochen]
   B[Filter einsetzen] --- C[Pulver einfüllen] --- D[Wasser einfüllen] --- E[Kaffeemaschine einschalten]
  end

  A[[Kaffee kochen]]

A ~~~ Unterprogramm
%% A ~~~ Unterprogramm = unsichtbare Verbindung zur Positionssteuerung
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 70.0%;justify-content: flex-start;">
<dl>
<dt>Rechteck mit doppelten, vertikalen Linien (Nummer 7.2.4)</dt>
<dd>
Hinweis auf ein an anderer Stelle dokumentiertes Programm
</dd>
</dl>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell quarto-layout-cell" style="flex-basis: 30.0%;justify-content: flex-start;">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
  ID0([Beginn Kaffeepause]) --- A 
  A{durstig} --&gt;|ja|C[[Kaffee kochen]] --- D[Kaffee trinken]
  A          --&gt;|nein|E[warten]
  D --- Z
  E ---- Z
  Z([Kaffepause Ende])

%% Kommentar: die Anzahl der Striche steuert die Position einer Zelle
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 70.0%;justify-content: flex-start;">
<dl>
<dt>Verbindung (Nummer 6.3.1)</dt>
<dd>
Prozessketten werden mit Linien oder Pfeilen verbunden. Die Verbindungen sind von links nach rechts bzw. von oben nach unten orientiert, Abweichungen davon müssen mit Pfeilspitzen gekenzeichnet werden.
</dd>
<dd>
Sind mehrere Ausgänge mit Bedingungen verknüpft, müssen diese durch Beschriftung an den Verbindungslinien kenntlich gemacht werden.
</dd>
<dd>
Mehrere Verbindungen zu einem Sinnbild können zu einer Verbindung zusammengeführt werden. Sich kreuzende Verbindungslinien sollten aber vermieden werden. Diese stellen keine Zusammenführung dar. <strong>Anmerkung: Mermaid (und auch Graphviz) scheinen diese Funktion nicht zu beherrschen</strong>
</dd>
</dl>
</div>
</div>
</div>
<p><span class="citation" data-cites="DIN-66001-1983">(<a href="#ref-DIN-66001-1983" role="doc-biblioref">DIN 1983</a>)</span></p>
<div id="wrn-DIN66001" class="callout callout-style-simple callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis&nbsp;1: Darstellung von Daten nach DIN 66001
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Die DIN 66001 definiert auch Sinnbilder zur Darstellung von Daten. Die Norm regelt aber für Programmablaufpläne: “Daten werden nicht dargestellt. Siehe Beispiel in Abschnitt A.2.” <span class="citation" data-cites="DIN-66001-1983">(<a href="#ref-DIN-66001-1983" role="doc-biblioref">DIN 1983, 2</a>)</span>. Gleichwohl sind im Beispiel A.2 spezfische Typen von Daten dargestellt, beispielsweise manuell oder maschinell zu verarbeitende Daten <span class="citation" data-cites="DIN-66001-1983">(<a href="#ref-DIN-66001-1983" role="doc-biblioref">DIN 1983, 13–14</a>)</span>.</p>
<p>Jedoch sind die in den Nummern 6.2.2 bis 6.2.10 definierten Sinnbilder für spezifische Datentypen nicht in allen Diagrammwerkzeugen vollständig verfügbar. Dies betrifft:</p>
<ul>
<li><p><a href="https://graphviz.org/doc/info/shapes.html">Graphviz</a> (z. B. maschinell zu verarbeitende Daten entsprechend Nummer 6.2.2)</p></li>
<li><p><a href="https://mermaid.js.org/syntax/flowchart.html#node-shapes">Mermaid</a> (z. B. maschinell zu verarbeitende Daten entsprechend Nummer 6.2.2)</p></li>
<li><p>Bürosoftwarepaket LibreOffice (z. B. manuell zu verarbeitende Daten entsprechend Nummer 6.2.3)</p></li>
</ul>
<p>In der Darstellung von Programmablaufplänen ist die Verwendung des Sinnbilds Nr. 6.2.1 Daten allgemein üblich.</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[30, 70]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 30.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skript/00-bilder/din-daten-allgemein.svg" class="img-fluid figure-img"></p>
<figcaption>&nbsp;</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 70.0%;justify-content: flex-start;">
<dl>
<dt>Daten (Nummer 6.2.1)</dt>
<dd>
Darstellung für Daten oder Datenträger allgemein
</dd>
</dl>
</div>
</div>
</div>
<!-- Hinweis: Aus technischen Gründen handelt es sich um eine gerenderte Grafik (Quarto issue #9677). -->
</div>
</div>
</div>
<section id="werkzeuge-zur-erstellung-von-flussdiagrammen" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="werkzeuge-zur-erstellung-von-flussdiagrammen">Werkzeuge zur Erstellung von Flussdiagrammen</h3>
<p>Flussdiagramme können auf unterschiedliche Weise erstellt werden:</p>
<ul>
<li><p>mit Stift und Papier,</p></li>
<li><p>mit Bürosoftwarepaketen wie LibreOffice,</p></li>
<li><p>Visualisierungsprogrammen wie <a href="https://graphviz.org/">Graphviz</a> oder <a href="https://mermaid.js.org/">Mermaid</a>,</p></li>
<li><p>mit spezialisierten Paketen wie <a href="https://cran.r-project.org/web/packages/DiagrammeR/index.html">DiagrammeR</a> oder <a href="https://schemdraw.readthedocs.io/en/latest/elements/flow.html">Schemdraw</a>.</p></li>
</ul>
<p>Der Funktionsumfang und die Syntax unterscheiden sich und jedes Werkzeug hat eigene Stärken. Mermaid, Graphviz und Schemdraw sind deklarative Zeichenwerkzeuge, mit denen Flussdiagramme (und andere Grafiken) geschrieben und graphisch umgesetzt werden können. Mermaid hat eine einfache, intuitive Syntax. Graphviz erlaubt mehr Gestaltungsmöglichkeiten (benötigt in Python aber eine lokale Systeminstallation). Das Python-Modul Schemdraw unterstützt eine an Pythoncode angelehnte Syntax und bietet einen einfachen Zugriff auf DIN-konforme Knoten und Kanten.</p>
<div id="nte-flowcharts" class="callout callout-style-default callout-note callout-titled" title="Flussdiagramme in Python und R erstellen">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Beispiel&nbsp;2: Flussdiagramme in Python und R erstellen
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true" href="">Codebeispiel Python</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false" href="">Schemdraw in Python</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-3" role="tab" aria-controls="tabset-4-3" aria-selected="false" href="">Codebeispiel R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-4" role="tab" aria-controls="tabset-4-4" aria-selected="false" href="">Mermaid in R</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="cell">
<pre class="raw cell-code"><code># Flussdiagramm mit Schemdraw und Graphviz in Python

## Schemdraw
import subprocess
subprocess.call(['pip', 'install', 'schemdraw'])
import schemdraw

from schemdraw.flow import *

with schemdraw.Drawing() as d:
    # durchgehender Prozess in korrekter Reihenfolge von Start bis Ende
    d+= Start().label("Mittagspause")
    d+= Line().down()
    d+= Box().label("Kartoffeln abzählen")
    d+= Line().down()
    d+= (mit_Schale := Decision(S = "Ja", E = "Nein").label("Mit Schale?"))
    d+= Arrow().at(mit_Schale.S)
    d+= (kochen := Box().label("Kartoffeln kochen"))
    d+= Line().down()
    d+= Box().label("Kartoffeln essen")
    d+= Line().down()
    d+= Start().label("Pause Ende")

    # alternativer Ast der Verzweigung
    d+= Arrow().right().at(mit_Schale.E)
    d+= (schälen := Box().label("Kartoffeln schälen"))
    d+= Wire("|-", arrow = "-&gt;").at(schälen.S).to(kochen.E) # .S + .E (oder andere Richtungsangaben) müssen gesetzt werden, |- definiert zunächst vertikale, rechtwinkelige Kante
    
     d.draw()
    # d.save("Kartoffeln.svg")

## Graphviz
## benötigt eine lokale Installation von Graphviz https://graphviz.org/download/

import subprocess
subprocess.call(['pip', 'install', 'graphviz']) # installiert das Modul graphviz
import graphviz

dot = graphviz.Digraph(name = "Kartoffeln")

### Start / Ende
dot.node(name = "Mittagspause", shape = "Mrecord") # optional label
dot.node(name = "Pause Ende", shape = "Mrecord")

### Anweisungen
dot.node(name = "Kartoffeln abzählen", shape = "box")
dot.node(name = "Kartoffeln schälen", shape = "box")
dot.node(name = "Kartoffeln kochen", shape = "box")
dot.node(name = "Kartoffeln essen", shape = "box")

### Entscheidung
dot.node(name = "mit Schale", shape = "diamond")
    
### Kanten
dot.edge("Mittagspause", "Kartoffeln abzählen", arrowhead = "none")
dot.edge("Kartoffeln abzählen", "mit Schale", arrowhead = "none")
dot.edge("mit Schale", "Kartoffeln kochen", label = "Ja")
dot.edge("mit Schale", "Kartoffeln schälen", label = "nein")
dot.edge("Kartoffeln schälen", "Kartoffeln kochen", arrowhead = "none")
dot.edge("Kartoffeln kochen", "Kartoffeln essen", arrowhead = "none")
dot.edge("Kartoffeln essen", "Pause Ende", arrowhead = "none")

dot.render("Kartoffeln.gv", cleanup = True, view = True)
</code></pre>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pseudocode_files/figure-html/python-schemdraw-1.png" class="img-fluid figure-img" width="582"></p>
<figcaption>Flussdiagramm mit Schemdraw</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-4-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-3-tab">
<pre><code># Flussdiagramm mit DiagrammeR in R

install.packages("DiagrammeR")
library("DiagrammeR")

## Mermaid
DiagrammeR::mermaid("
  graph TD
    0(Mittagspause)
    A[Kartoffeln abzählen]
    B{mit Schale}
    D[Kartoffeln kochen]
    E[Kartoffeln essen]
    S[Kartoffeln schälen]
    Z(Pause Ende)
    
    0---A
    A---B
    B--&gt;|ja|D
    B--&gt;|nein|S
    S---D
    D---E
    E---Z
")

## Graphviz
DiagrammeR::grViz("

  graph Kartoffeln {
  
  # defining nodes
  node [shape = Mrecord]
  
    Mittagspause; Pause_Ende
  
  node [shape = box]
  
    Kartoffeln_abzählen
    Kartoffeln_schälen
    Kartoffeln_kochen
    Kartoffeln_essen
    
  node[shape = diamond]
  
    mit_Schale
    
  # defining edges
    Mittagspause -- Kartoffeln_abzählen
    Kartoffeln_abzählen -- mit_Schale
      mit_Schale -- Kartoffeln_kochen[dir = forward label=ja]
      mit_Schale -- Kartoffeln_schälen[dir = forward label=nein]
        Kartoffeln_schälen -- Kartoffeln_kochen
    Kartoffeln_kochen -- Kartoffeln_essen
    Kartoffeln_essen -- Pause_Ende
  }
")</code></pre>
</div>
<div id="tabset-4-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-4-tab">
<!-- Der Mermaid-Code läuft in Quarto, aber nicht im HTML (lässt Mermaid Engine abstürzen). HTML-Kommentare werden vom Mermaid-Code aufgelöst. Deshalb Einbinden als Grafik. https://github.com/quarto-dev/quarto-cli/issues/9693 -->
<!-- .svg fails to render with arrow heads -->
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skript/00-bilder/mermaid-in-r.png" class="img-fluid figure-img"></p>
<figcaption>&nbsp;</figcaption>
</figure>
</div>
<!-- Hinweis: Aus technischen Gründen handelt es sich um eine gerenderte Grafik (Quarto issue #9693). -->
</div>
</div>
</div>
</div>
</div>
</div>
<p>&nbsp;</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true" href="">Übungsaufgabe zählen</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false" href="">Musterlösung Pseudocode</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-3" role="tab" aria-controls="tabset-5-3" aria-selected="false" href="">Musterlösung Mermaid</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-4" role="tab" aria-controls="tabset-5-4" aria-selected="false" href="">Musterlösung Flussdiagramm</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<p><strong>Erstellen Sie ein Flussdiagramm für ein Programm, das von 1-10 und von 15 bis 20 zählt.</strong></p>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<pre><code>i = 0
SOLANGE i kleiner als 10 TUE
  erhöhe i um 1
  Ausgabe i
i = 14
SOLANGE i kleiner als 20 TUE
  erhöhe i um 1
  Ausgabe i</code></pre>
</div>
<div id="tabset-5-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-3-tab">
<pre class="raw"><code>---
title: Zähle von 1-10 und von 15-20
---
flowchart TD
Start([Start])
initialisieren1[i = 0]
initialisieren2[i = 14]
Schleife1{i kleiner 10}
Schleife2{i kleiner 20}
Erhöhe1[i = i + 1]
Erhöhe2[i = i + 1]
Ausgabe1[Gebe i aus]
Ausgabe2[Gebe i aus]
Ende([Ende])

Start --- initialisieren1
initialisieren1 --- Schleife1
    
    Schleife1 --&gt;|nein| initialisieren2 --- Schleife2
        Schleife2 --&gt;|ja| Erhöhe2 --- Ausgabe2 --&gt; Schleife2
        Schleife2 --&gt;|nein| Ende

    Schleife1 --&gt;|ja| Erhöhe1 --- Ausgabe1 --&gt; Schleife1

%% unsichtbare Verbindungen zur Positionssteuerung
    Ausgabe1 ~~~ Schleife2
    Ausgabe2 ~~~ Ende
</code></pre>
</div>
<div id="tabset-5-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-4-tab">
<!-- .svg fails to render with arrow heads -->
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="aufgaben/00-bilder/musterloesung-flussdiagramm.png" class="img-fluid figure-img"></p>
<figcaption>Flussdiagramm mit DiagrammeR in R</figcaption>
</figure>
</div>
<!-- Hinweis: Aus technischen Gründen handelt es sich um eine gerenderte Grafik (Quarto issue #9693). -->
</div>
</div>
</div>
</section>
</section>
</section>
<section id="musterlösungen" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Musterlösungen</h1>
<div id="tip-Hefezopf" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;3: Hefezopf backen
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Für die Zubereitung des Hefezopfes werden mindestens drei Stunden benötigt. Der Teig (bzw. die Hefemischung) muss verteilt über mehrere Schritte insgesamt 120 Minuten gehen und nach dem Backen auskühlen. Aufgrund der langen Wartezeiten können die Arbeitsschritte von einer Person durchgeführt werden, eine parallele Bearbeitung durch eine zweite Person spart nur wenig Zeit ein. Lisa darf natürlich trotzdem eine Stunde früher vorbei kommen, aber dann ruht der Teig zum letzten Mal, bäckt im Ofen oder kühlt bereits aus. Zutaten mitbringen muss sie nicht, die Zutatenliste ist vollständig.</p>
<pre><code># Zwischenschritt 1 - ca. 25 Minuten
## Eingabe: 250 ml Milch, 475 g Weizenmehl, 1 Prise Zucker, ½ Würfel Hefe
## Werkzeug: Schüssel, Sieb, Topf, Löffel, Geschirrtuch  
## Verarbeitung: Hefe in gezuckerter Milch lösen
## Ausgabe: Hefemischung, Mehl

BereiteHefemischung
  MehlSieben # benutze Sieb
  MehlHinzufügen        
  MuldeBilden # Mulde im Mehl bilden  
  HefeZerbröseln  
  HefeHinzufügen  
  MilchVorbereiten # benutze Topf
    **Solange** Milch &lt; lauwarm **Tue**  
      MilchErwärmen  
    ZuckerHinzufügen
    Verrühren # Milch und Zucker mit Löffel vermischen  
  MilchHinzufügen  
  Verrühren # Hefe und Milchmischung mit Löffel vermischen  
  TeigGeht(Zeit = 15 Minuten)  
    SchüsselAbdecken # benutze Geschirrtuch  
    WarmStellen

# Zwischenschritt 2 - ca. 75 Minuten
## Eingabe: Hefemischung, Mehl, 1 Ei, 60 g Zucker, 1 Prise Salz, 50 g Butter  
## Werkzeug: Schüssel, Rührgerät, Messer, Geschirrtuch
## Verarbeitung: Ei, Milch, Salz, Butter hinzugeben und verkneten  
## Ausgabe: Rohteig
    
BereiteTeig  
  ButterWürfeln # benutze Messer  
    # Ausgabe: n Butterwürfel
  **SOLANGE** TeigGeht **TUE**
    Warten  
  EiHinzufügen  
  MilchHinzufügen  
  ZuckerHinzufügen  
  SalzHinzufügen  
  Kneten(Zeit = 3 Min, Stufe = niedrig) # benutze Rührhaken  
  Kneten(Zeit = 5 Min, Stufe = hoch) # benutze Rührhaken  
  ButterHinzufügen  
    **SOLANGE** n &gt; 0 **TUE**  
      Kneten(Stufe = hoch)  
      ButterwürfelHinzufügen  
      n = n - 1
    Kneten(Zeit = 5 Min, Stufe = hoch) # benutze Rührhaken
  TeigGeht(Zeit = 60 Minuten)  
    SchüsselAbdecken # benutze Geschirrtuch  
    WarmStellen

# Zwischenschritt 3 - ca. 55 Minuten
## Eingabe: Rohteig, etwas Mehl
## Verarbeitung: Rohteig zu Teigzopf verarbeiten
## Werkzeug: Blech, Backpapier, Geschirrtuch
## Ausgabe: Teigzopf

ZopfFormen  
  BackpapierAufBlechLegen  
  ArbeitsflächeBemehlen  
  TeigAufArbeitsflächeLegen  
  TeigTeilen(Stücke = 3)  
    # Ausgabe = n Teigstücke  
  TeigRollen  
    **SOLANGE** n &gt; 0 **TUE**  
      TeigstückRollen(Länge = 40 cm)  
      n = n - 1  
  ZopfErzeugen  
    RollenFlechten  
    EndenVerdrehen  
  ZopfAufBackpapierLegen  
  TeigGeht(Zeit = 45 Minuten)  
    ZopfAbdecken # benutze Geschirrtuch 
    WarmStellen  

# Zwischenschritt 4 - ca. 40 Minuten
## Eingabe: Teigzopf, etwas Milch, etwas Hagelzucker
## Werkzeug: Pinsel, Ofen
## Verarbeitung: Zopf bestreichen, bestreuen und backen
## Ausgabe: Hefezopf (gebacken)

ZopfBacken  
  OfenVorheizen  
    **WENN** UmluftVerfügbar **DANN**   
      Modus = Umluft  
      Temperatur = 180 Grad  
    **SONST**  
      Modus = Ober- / Unterhitze  
      Temperatur = 200 Grad  
  ZopfMitMilchBestreichen # benutze Pinsel
  ZopfMitHagelzuckerBestreuen
  ZopfBacken
    BlechInOfenStellen
    **SOLANGE** Zopf &lt; leicht bräunlich **TUE**
      BlechImOfenLassen
    BlechHerausholen
  ZopfAuskühlen
    **SOLANGE** Zopf &gt; Zimmertemperatur **TUE**
      Warten
</code></pre>
</div>
</div>
</div>
<div id="tip-Meerschweinchen" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;4: Vitamin C bei Meerschweinchen
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code># Schritt 1 – Datensatz einlesen
## Eingabe: URL
## Werkzeug: Browser
## Verarbeitung: Speichern der Rohdaten
## Ausgabe: kommaseparierte Datei ToothGrowth.csv

HoleDatensatzVonURL
DatensatzSpeichern

# Schritt 2 – Mittelwertvergleich
## Eingabe: ToothGrowth.csv
## Werkzeug: IDE
## Verarbeitung: Mittelwerte für Teildatensätze bilden
## Ausgabe: Tabelle der Mittelwerte nach Dosis und Verabreichungsmethode

ZeilennummernBestimmen
  Zeilennummern(supp = OJ)
  Zeilennummern(supp = VC)
  Zeilennummern(dose = 0.5)
  Zeilennummern(dose = 1)
  Zeilennummern(dose = 2)
TeildatensätzeBilden # über Kriterium oder über Zeilennummern
    TeildatensatzSupp = OJ
        TeildatensatzDose = 0.5
        TeildatensatzDose = 1
        TeildatensatzDose = 2
    TeildatensatzSupp = VC
        TeildatensatzDose = 0.5
        TeildatensatzDose = 1
        TeildatensatzDose = 2
MittelwerteErmitteln
    MittelwertLen(Datensatz)
    MittelwerteTeildatensätze
        MittelwertLen(TeildatensatzSupp = OJ &amp; Dose = 0.5)
        MittelwertLen(TeildatensatzSupp = OJ &amp; Dose = 1)
        MittelwertLen(TeildatensatzSupp = OJ &amp; Dose = 2)
        MittelwertLen(TeildatensatzSupp = VC &amp; Dose = 0.5)
        MittelwertLen(TeildatensatzSupp = VC &amp; Dose = 1)
        MittelwertLen(TeildatensatzSupp = VC &amp; Dose = 2)
TabelleErstellen
    Spalten = OJ, VC
    Zeilen = Dosis
    Zellen = MittelwerteLen
TabelleAusgeben

# Schritt 3 – graphische Darstellung
## Eingabe: ToothGrowth.csv
## Werkzeug: Funktion für Boxplot
## Verarbeitung: Boxplot nach Dosis und Methode erzeugen
## Ausgabe: Boxplots nach Dosis und Verabreichungsmethode

Boxplot(Len nach Dosis &amp; Methode)
    BoxplotErstellen
    VerabreichungsmethodeFarblichUnterscheiden
    LegendeEintragen
SpeichereBoxplot</code></pre>
</div>
</div>
</div>
</section>
<section id="das-wichtigste" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Das Wichtigste</h1>
<p>In welcher Form und wie detailliert Sie Pseudocode formulieren, hängt von Ihrem Kenntnisstand und Ihrem Ziel ab. Die Entwicklung von Pseudocode kann als Kreativitätstechnik ohne formale Vorgaben eingesetzt werden, in detaillierter Form bei der Ausarbeitung einer algorithmischen Lösung helfen oder visuell in Form eines Flussdiagramms Ihre Kommunikation mit Dritten unterstützen.</p>
</section>
<section id="lernzielkontrolle" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Lernzielkontrolle</h1>
<section id="kompetenzquiz" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="kompetenzquiz"><span class="header-section-number">7.1</span> Kompetenzquiz</h2>
<ol class="example" type="1">
<li>Schreiben Sie ein Programm in Pseudocode, das alle geraden Zahlen bis 10 ausgibt.</li>
</ol>
<textarea id="“quiz-1" name="quiz-1”" rows="4" cols="50"></textarea>
<p>&nbsp;</p>
<ol start="2" class="example" type="1">
<li>Fehler im Pseudocode finden.</li>
</ol>
<p>Ein:e Freund:in zeigt Ihnen den Pseudocode eines Programms, das prüfen soll, ob Buchstaben groß oder klein geschrieben sind. Die Ausgabe klappt aber nur für klein geschriebene Buchstaben. Finden Sie den Fehler?</p>
<div class="cell">
<pre class="raw cell-code"><code>
text = Eingabe("Bitte geben Sie Ihren Text ein.")
zeichen_liste = TeileZeichenweiseInListeAuf(text)

FÜR JEDES element IN zeichen_liste TUE

  Wenn Dezimalwert(element) &gt;= 97 UND Dezimalwert(element) &lt;= 122 TUE
    Schreibe("Das Zeichen ", element, "ist klein geschrieben.")

    Wenn Dezimalwert(element) &gt;= 65 UND Dezimalwert(element) &lt;= 90 TUE
      Schreibe("Das Zeichen ", element, "ist groß geschrieben.")
</code></pre>
</div>
<p>&nbsp;</p>
<ol start="3" class="example" type="1">
<li>Zeichnen Sie ein Flussdiagramm des korrekten Programms.</li>
</ol>
<div id="tip-Kompetenzquiz" class="callout callout-style-default callout-tip callout-titled" title="Lösungen">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;6: Lösungen
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Lösung 1:</p>
<div class="cell">
<pre class="raw cell-code"><code>i = 1 
SOLANGE i kleiner gleich 10
  WENN i Modulo 2 gleich 0 TUE
    Ausgabe i
  Erhöhe i um 1</code></pre>
</div>
<p>Lösung 2: Die Prüfung der Bedingungen für groß geschriebenen Buchstaben (Dezimalwert(element) &gt;= 65 UND Dezimalwert(element) &lt;= 90) erfolgt im Anweisungsblock, wenn ein Buchstabe klein geschrieben ist (Dezimalwert(element) &gt;= 97 UND Dezimalwert(element) &lt;= 122 ). Der Wahrheitswert dieser Bedingung ist falsch, wenn ein Buchstabe groß geschrieben ist. Die folgenden Anweisungen werden deshalb nicht ausgeführt, wenn element einen Großbuchstaben enthält. Durch korrektes Einrücken kann das Problem gelöst werden.</p>
<div class="cell">
<pre class="raw cell-code"><code>
text = Eingabe("Bitte geben Sie Ihren Text ein.")
zeichen_liste = TeileZeichenweiseInListeAuf(text)

FÜR JEDES element IN zeichen_liste TUE

  Wenn Dezimalwert(element) &gt;= 97 UND Dezimalwert(element) &lt;= 122 TUE
    Schreibe("Das Zeichen ", element, "ist klein geschrieben.")

  # korrigierte Einrückung
  Wenn Dezimalwert(element) &gt;= 65 UND Dezimalwert(element) &lt;= 90 TUE
    Schreibe("Das Zeichen ", element, "ist groß geschrieben.")
</code></pre>
</div>
<p>Lösung 3:</p>
<div id="tip-Kompetenzquiz-flussdiagramm" class="callout callout-style-default callout-tip callout-titled" title="Mermaid Diagramm">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;5: Mermaid Diagramm
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><img src="skript/00-bilder/mermaid-diagram-buchstaben.svg" class="img-fluid" style="width:80.0%" alt="Ein Flussdiagramm für den in Lösung 2 gezeigten Pseudocode."></p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="übungen" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="übungen"><span class="header-section-number">7.2</span> Übungen</h2>
<section id="börsenstrategie-entwickeln" class="level3">
<h3 class="anchored" data-anchor-id="börsenstrategie-entwickeln">Börsenstrategie entwickeln</h3>
<p>Sie möchten den möglichen Ertrag einer Turnaround-Strategie an der Börse bewerten. Ihre Idee besteht darin, einen Aktienindex zu kaufen, wenn dieser mindestens 30 Prozent vom Allzeithoch der letzten drei Jahre gefallen ist. Sie spekulieren mit Ihrer Strategie darauf, dass sich der Aktienindex wieder erholt und Sie durch den günstigen Einstieg eine bessere Rendite als bei regelmäßigen, kursunabhängigen Zukäufen erzielen. Der Vergleichszeitraum beträgt 30 Jahre (Beginn und Ende können Sie selbst festlegen).</p>
<p><strong>Testen Sie Ihre Strategie anhand des S&amp;P500.</strong></p>
<p>Parameter: 5.000 Dollar Startkapital, über 30 Jahre monatlich zusätzlich 500 Dollar investierbares Kapital, Dividenden werden im Folgemonat reinvestiert bzw. bis zum nächsten Kursrückgang angespart, Strategie: Buy &amp; Hold (keine Verkäufe), Kurseinbruch: 30 Prozent gegenüber Allzeithoch der letzten 3 Jahre.</p>
<ul>
<li><p>Optional: In wie vielen 30-Jahresperioden wäre Ihre Turnaround-Strategie besser gewesen als stetiges Zukaufen?</p></li>
<li><p>Optional: Wie verändert sich das Verhältnis, wenn der Schwellenwert für den Kurseinbruch verändert wird (20 oder 40 Prozent)?</p></li>
</ul>
<p>Ein Datensatz des S&amp;P500 mit Monatsdaten von 1871 bis 2024 ist auf der <a href="https://shillerdata.com/">Webseite</a> von Robert Shiller verfügbar (<a href="https://img1.wsimg.com/blobby/go/e5e77e0b-59d1-44d9-ab25-4763ac982e53/downloads/ie_data.xls?ver=1712069253887">Direktlink zur XLS-Datei</a>).</p>
<div id="wrn-SP500" class="callout callout-style-simple callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis&nbsp;2: Datensatzbeschreibung S&amp;P500
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Der Datensatz liegt in monatlicher Auflösung (<strong>Date</strong>) vor. Neben dem Kurs (<strong>Price</strong>) sind die ausgeschütteten Dividenden (<strong>Dividend</strong>) festgehalten.<br>
<em>Hinweis: Der Datensatz liegt als Exceldatei vor und wurde aus Gründen der Übersichtlichkeit leicht bearbeitet (Anpassung der Spaltennamen, Formatierung Spalte Date, Runden der Spalten Price und Dividend). Bitte beachten Sie, dass wenn Sie den Datensatz selbst abrufen, das Erscheinungsbild entsprechend abweicht.</em></p>
<table class="table">
<thead>
<tr class="header">
<th>#</th>
<th>Date</th>
<th>Price</th>
<th>Dividend</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1871.01</td>
<td>4.44</td>
<td>0.26</td>
</tr>
<tr class="even">
<td>2</td>
<td>1871.02</td>
<td>4.50</td>
<td>0.26</td>
</tr>
<tr class="odd">
<td>3</td>
<td>1871.03</td>
<td>4.61</td>
<td>0.26</td>
</tr>
<tr class="even">
<td>4</td>
<td>1871.04</td>
<td>4.74</td>
<td>0.26</td>
</tr>
<tr class="odd">
<td>5</td>
<td>1871.05</td>
<td>4.86</td>
<td>0.26</td>
</tr>
<tr class="even">
<td>6</td>
<td>1871.06</td>
<td>4.82</td>
<td>0.26</td>
</tr>
<tr class="odd">
<td>7</td>
<td>1871.07</td>
<td>4.73</td>
<td>0.26</td>
</tr>
<tr class="even">
<td>8</td>
<td>1871.08</td>
<td>4.79</td>
<td>0.26</td>
</tr>
<tr class="odd">
<td>9</td>
<td>1871.09</td>
<td>4.84</td>
<td>0.26</td>
</tr>
<tr class="even">
<td>10</td>
<td>1871.10</td>
<td>4.59</td>
<td>0.26</td>
</tr>
<tr class="odd">
<td>11</td>
<td>1871.11</td>
<td>4.64</td>
<td>0.26</td>
</tr>
<tr class="even">
<td>12</td>
<td>1871.12</td>
<td>4.74</td>
<td>0.26</td>
</tr>
<tr class="odd">
<td>1828</td>
<td>2023.04</td>
<td>4121.47</td>
<td>68.38</td>
</tr>
<tr class="even">
<td>1829</td>
<td>2023.05</td>
<td>4146.17</td>
<td>68.54</td>
</tr>
<tr class="odd">
<td>1830</td>
<td>2023.06</td>
<td>4345.37</td>
<td>68.71</td>
</tr>
<tr class="even">
<td>1831</td>
<td>2023.07</td>
<td>4508.08</td>
<td>68.91</td>
</tr>
<tr class="odd">
<td>1832</td>
<td>2023.08</td>
<td>4457.36</td>
<td>69.11</td>
</tr>
<tr class="even">
<td>1833</td>
<td>2023.09</td>
<td>4409.09</td>
<td>69.31</td>
</tr>
<tr class="odd">
<td>1834</td>
<td>2023.10</td>
<td>4269.40</td>
<td>69.64</td>
</tr>
<tr class="even">
<td>1835</td>
<td>2023.11</td>
<td>4460.06</td>
<td>69.97</td>
</tr>
<tr class="odd">
<td>1836</td>
<td>2023.12</td>
<td>4685.05</td>
<td>70.30</td>
</tr>
<tr class="even">
<td>1837</td>
<td>2024.01</td>
<td>4815.61</td>
<td>70.48</td>
</tr>
<tr class="odd">
<td>1838</td>
<td>2024.02</td>
<td>5011.96</td>
<td>70.65</td>
</tr>
<tr class="even">
<td>1839</td>
<td>2024.03</td>
<td>5170.57</td>
<td>70.82</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>

</section>
</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">Literatur</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Pseudocode-was-ist" class="csl-entry" role="listitem">
AAU, Informatik-Werkstatt. 2019. <span>„Was ist ein Pseudocode?“</span> 2019. <a href="https://www.rfdz-informatik.at/wp-content/uploads/2020/10/RE_I_Pseudocode.pdf">https://www.rfdz-informatik.at/wp-content/uploads/2020/10/RE_I_Pseudocode.pdf</a>.
</div>
<div id="ref-Crampton.1947" class="csl-entry" role="listitem">
Crampton, E. W. 1947. <span>„THE GROWTH OF THE ODONTOBLASTS OF THE INCISOR TOOTH AS A CRITERION OF THE VITAMIN C INTAKE OF THE GUINEA PIG“</span>. <em>The Journal of Nutrition</em> 33 (5): 491–504. <a href="https://doi.org/10.1093/jn/33.5.491">https://doi.org/10.1093/jn/33.5.491</a>.
</div>
<div id="ref-DIN-66001-1983" class="csl-entry" role="listitem">
DIN. 1983. <span>„DIN 66001: Informationsverarbeitung. Sinnbilder und ihre Anwendung“</span>. Berlin: <span>Beuth Verlag GmbH</span>. 1983. <a href="https://doi.org/10.31030/1300312">https://doi.org/10.31030/1300312</a>.
</div>
<div id="ref-Scheuermann2016" class="csl-entry" role="listitem">
Scheuermann, Ulrike. 2016. <em>Schreibdenken: Schreiben als Denk- und Lernwerkzeug nutzen und vermitteln</em>. 3. Aufl. utb.
</div>
<div id="ref-R-for-Data-Science" class="csl-entry" role="listitem">
Wickham, Hadley, Mine Çetinkaya-Rundel, und Garrett Grolemund. 2023. <span>„R for data science: Import, tidy, transform, visualize, and model data“</span>. Beijing; Boston; Farnham; Sebastopol; Tokyo: O’Reilly. 2023. <a href="https://r4ds.hadley.nz/">https://r4ds.hadley.nz/</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>